services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=preference_center
    ports:
      - '5432:5432'
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
